---
kind: Service
apiVersion: v1

metadata:
    name: web-v1

spec:
    selector:
        app.kubernetes.io/name: assets-web
        app.kubernetes.io/version: v1
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: assets
    type: ClusterIP
    ports:
        - name: http
          port: 8081
          targetPort: http
