---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-assets

resources:
    - ../../base
    - configmaps.yaml
    - secrets.yaml
    - podmonitor.yaml
    - ingress.yaml
    - middlewares.yaml
    - pvc.yaml

labels:
  - pairs:
      app.kubernetes.io/name: assets-web
      app.kubernetes.io/version: v1
      app.kubernetes.io/component: web
      app.kubernetes.io/part-of: assets
      com.sweetrpg/env: local
    includeSelectors: false
    includeTemplates: true

generatorOptions:
    disableNameSuffixHash: true

images:
  - name: assets-web
    newName: ghcr.io/sweetrpg/assets-web
    newTag: v0.0.1
