---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor

metadata:
    name: sweetrpg-assets-web
    labels:
        release: prometheus

spec:
    namespaceSelector:
        matchNames:
            - sweetrpg-assets
    podMetricsEndpoints:
        - port: http
    selector:
        matchLabels:
            app.kubernetes.io/name: assets-web
            app.kubernetes.io/version: v1
            app.kubernetes.io/component: web
            app.kubernetes.io/part-of: assets
